SELECT NOTIF.OBJECT_ID "OBJECT_ID", NOTATMES.VALUE "MESSAGE", NOTATSD.DATE_VALUE "SEND_DATE", NOTATED.DATE_VALUE "EXECUTED_DATE",
USR.OBJECT_ID "AUTHOR_ID", EXBY.OBJECT_ID "EXECUTED_BY", ORDERS.OBJECT_ID "ORDER_ID", NOTTYPE.NAME "NOTIFICATION_TYPE"
FROM OBJECTS NOTIF, OBJECTS USR, OBJECTS ORDERS, OBJECTS EXBY, OBJECTS NOTTYPE, ATTRIBUTES NOTATMES, ATTRIBUTES NOTATSD, ATTRIBUTES NOTATED,
ATTRTYPE UREFA, ATTRTYPE OREFA, ATTRTYPE EREFA, ATTRTYPE NREFA, OBJREFERENCE NREF, OBJREFERENCE UREF, OBJREFERENCE OREF, OBJREFERENCE EREF
WHERE NOTIF.OBJECT_TYPE_ID=4
AND USR.OBJECT_TYPE_ID=3
AND ORDERS.OBJECT_TYPE_ID=2
AND NOTTYPE.OBJECT_TYPE_ID=11
AND EXBY.OBJECT_TYPE_ID=3
AND NOTATED.ATTR_ID=25
AND NOTATMES.ATTR_ID=22
AND NOTATSD.ATTR_ID=23
AND OREFA.ATTR_ID=27
AND UREFA.ATTR_ID=21
AND EREFA.ATTR_ID=24
AND NREFA.ATTR_ID=26
AND NOTIF.OBJECT_ID=NOTATMES.OBJECT_ID
AND NOTIF.OBJECT_ID=NOTATSD.OBJECT_ID
AND NOTIF.OBJECT_ID=NOTATED.OBJECT_ID
AND NOTIF.OBJECT_ID=UREF.OBJECT_ID
AND NOTIF.OBJECT_ID=OREF.OBJECT_ID
AND NOTIF.OBJECT_ID=EREF.OBJECT_ID
AND NOTIF.OBJECT_ID=NREF.OBJECT_ID
AND NOTIF.OBJECT_TYPE_ID=EREFA.OBJECT_TYPE_ID
AND NOTIF.OBJECT_TYPE_ID=OREFA.OBJECT_TYPE_ID
AND NOTIF.OBJECT_TYPE_ID=UREFA.OBJECT_TYPE_ID
AND NOTIF.OBJECT_TYPE_ID=NREFA.OBJECT_TYPE_ID
AND NREFA.ATTR_ID=NREF.ATTR_ID
AND OREFA.ATTR_ID=OREF.ATTR_ID
AND UREFA.ATTR_ID=UREF.ATTR_ID
AND EREFA.ATTR_ID=EREF.ATTR_ID
AND UREF.REFERENCE=USR.OBJECT_ID
AND EREF.REFERENCE=EXBY.OBJECT_ID
AND OREF.REFERENCE=ORDERS.OBJECT_ID
AND NREF.REFERENCE=NOTTYPE.OBJECT_ID;