SELECT USR.OBJECT_ID "USERID", USALOG.VALUE "LOGIN", USAPASS.VALUE "PASSWORD", RLENAME.VALUE "ROLE"
FROM OBJECTS USR, ATTRTYPE USTOROLE, OBJREFERENCE USTOROLEREF, OBJTYPE ROLETYPE, OBJECTS RLE, ATTRIBUTES USALOG, ATTRIBUTES USAPASS, ATTRIBUTES RLENAME
WHERE USR.OBJECT_TYPE_ID = 3 AND
ROLETYPE.OBJECT_TYPE_ID=10 AND
USALOG.ATTR_ID=15 AND
USAPASS.ATTR_ID=16 AND
RLENAME.ATTR_ID=39 AND
USALOG.OBJECT_ID = USR.OBJECT_ID AND
USAPASS.OBJECT_ID = USR.OBJECT_ID AND
RLENAME.OBJECT_ID = RLE.OBJECT_ID AND
USR.OBJECT_TYPE_ID = USTOROLE.OBJECT_TYPE_ID AND
USTOROLE.OBJECT_TYPE_ID_REF = ROLETYPE.OBJECT_TYPE_ID AND
USR.OBJECT_ID=USTOROLEREF.OBJECT_ID AND
USTOROLE.ATTR_ID = USTOROLEREF.ATTR_ID AND
RLE.OBJECT_ID =USTOROLEREF.REFERENCE AND
USALOG.VALUE='admin@mail.ru';