SELECT USERLOG.VALUE "email", USERPASS.VALUE "password",
USERFIN.VALUE "firstName", USERLAN.VALUE "lastName", USERAD.VALUE "additionalInfo",
USEROLE.VALUE "role"
FROM OBJECTS USERS, ATTRIBUTES USERLOG, ATTRIBUTES USERPASS,
ATTRIBUTES USERFIN, ATTRIBUTES USERLAN, ATTRIBUTES USERAD, ATTRIBUTES USEROLE,
OBJREFERENCE ROLEREF
WHERE USERS.OBJECT_TYPE_ID=3 AND
    USERLOG.ATTR_ID=15 AND
    USERPASS.ATTR_ID=16 AND
    USERFIN.ATTR_ID=17 AND
    USERLAN.ATTR_ID=18 AND
    USERAD.ATTR_ID=19 AND
    USEROLE.ATTR_ID=39 AND
    ROLEREF.ATTR_ID=20 AND
    ROLEREF.OBJECT_ID=USERS.OBJECT_ID AND
    ROLEREF.REFERENCE=USEROLE.OBJECT_ID AND
    USERS.OBJECT_ID=USERLOG.OBJECT_ID AND
    USERS.OBJECT_ID=USERPASS.OBJECT_ID AND
    USERS.OBJECT_ID=USERFIN.OBJECT_ID AND
    USERS.OBJECT_ID=USERLAN.OBJECT_ID AND
    USERS.OBJECT_ID=USERAD.OBJECT_ID
    ORDER BY USERFIN.VALUE;

/*
    old var:
    SELECT USERS.OBJECT_ID "USERID", USERLOG.VALUE "EMAIL", USERPASS.VALUE "PASSWORD",
    USERFIN.VALUE "FIRSTNAME", USERLAN.VALUE "LASTNAME", USERAD.VALUE "ADDINFO",
    USEROLE.VALUE "ROLE"
    FROM OBJECTS USERS, ATTRIBUTES USERLOG, ATTRIBUTES USERPASS,
    ATTRIBUTES USERFIN, ATTRIBUTES USERLAN, ATTRIBUTES USERAD, ATTRIBUTES USEROLE,
    OBJREFERENCE ROLEREF
    WHERE USERS.OBJECT_TYPE_ID=3 AND
        USERLOG.ATTR_ID=15 AND
        USERPASS.ATTR_ID=16 AND
        USERFIN.ATTR_ID=17 AND
        USERLAN.ATTR_ID=18 AND
        USERAD.ATTR_ID=19 AND
        USEROLE.ATTR_ID=39 AND
        ROLEREF.ATTR_ID=20 AND
        ROLEREF.OBJECT_ID=USERS.OBJECT_ID AND
        ROLEREF.REFERENCE=USEROLE.OBJECT_ID AND
        USERS.OBJECT_ID=USERLOG.OBJECT_ID AND
        USERS.OBJECT_ID=USERPASS.OBJECT_ID AND
        USERS.OBJECT_ID=USERFIN.OBJECT_ID AND
        USERS.OBJECT_ID=USERLAN.OBJECT_ID AND
        USERS.OBJECT_ID=USERAD.OBJECT_ID
        ORDER BY USERFIN.VALUE;
        */