SELECT USR.OBJECT_ID "OBJECTID", USROLE.VALUE "USEROLE"
FROM OBJECTS USR, ATTRIBUTES USROLE, ATTRTYPE USTOROLE, OBJREFERENCE USTOROLEREF, OBJTYPE ROLETYPE, OBJECTS RLE
WHERE USR.OBJECT_TYPE_ID = 3 AND
ROLETYPE.OBJECT_TYPE_ID=10 AND
USR.OBJECT_TYPE_ID = USTOROLE.OBJECT_TYPE_ID AND
USTOROLE.OBJECT_TYPE_ID_REF = ROLETYPE.OBJECT_TYPE_ID AND
RLE.OBJECT_TYPE_ID = ROLETYPE.OBJECT_TYPE_ID AND
USR.OBJECT_ID=USTOROLEREF.OBJECT_ID AND
USTOROLE.ATTR_ID = USTOROLEREF.ATTR_ID AND
USTOROLEREF.REFERENCE=RLE.OBJECT_ID AND
RLE.OBJECT_ID = USROLE.OBJECT_ID AND
USROLE.ATTR_ID = 39 AND
USR.OBJECT_ID=901;


SELECT USR.OBJECT_ID "OBJECTID", USTOROLEREF.REFERENCE "USEROLE.ID"
FROM OBJECTS USR, ATTRTYPE USTOROLE, OBJREFERENCE USTOROLEREF, OBJTYPE ROLETYPE
WHERE USR.OBJECT_TYPE_ID = 3 AND

ROLETYPE.OBJECT_TYPE_ID=10 AND
USR.OBJECT_TYPE_ID = USTOROLE.OBJECT_TYPE_ID AND
USTOROLE.OBJECT_TYPE_ID_REF = ROLETYPE.OBJECT_TYPE_ID AND
USR.OBJECT_ID=USTOROLEREF.OBJECT_ID AND
USTOROLE.ATTR_ID = USTOROLEREF.ATTR_ID AND

USR.OBJECT_ID=901;



SELECT USEROBJ.OBJECT_ID "USERID", USALOG.VALUE "LOGIN", USAPASS.VALUE "PASSWORD", USAROL.VALUE "ROLE"
FROM OBJECTS USEROBJ, OBJECTS USEROLE, ATTRIBUTES USALOG, ATTRIBUTES USAPASS