CREATE INDEX obj_ot_ind ON OBJECTS (OBJECT_TYPE_ID);
CREATE INDEX obj_par_ind ON OBJECTS (PARENT_ID);
CREATE INDEX objt_ot_ind ON OBJTYPE (OBJECT_TYPE_ID);
CREATE INDEX attrt_ot_ind ON ATTRTYPE (OBJECT_TYPE_ID);
CREATE INDEX attrt_at_ind ON ATTRTYPE (ATTR_ID);
CREATE INDEX attr_at_ind ON ATTRIBUTES (ATTR_ID);
COMMIT;